// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqfdimwvlfmfkqdeqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcWZkaW13dmxmbWZrcWRlcWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTUwNTksImV4cCI6MjA2Nzg3MTA1OX0.uwNTECvOwzqBiBSJK8HbWdK9u5ZZq2lIoiv8ahKA3fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});